package com.example.ui


import androidx.compose.runtime.Composable

import androidx.compose.runtime.CompositionLocalProvider

import androidx.compose.runtime.ProvidableCompositionLocal

import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage(val code: String, val displayName: String) {
    ENGLISH("en", "English"),
    AMHARIC("am", "አማርኛ (Amharic)"),
    SOMALI("so", "Af-Soomaali (Somali)")
}

class Localization(val language: AppLanguage) {
    private val strings = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_name" to "E-Suuq",
            "tagline" to "Ethiopia's Leading Super-App",
            "role_buyer" to "Buyer",
            "role_seller" to "Seller",
            "role_delivery" to "Delivery Personnel",
            "home" to "Home",
            "search" to "Search",
            "manage_store" to "Store",
            "manage_delivery" to "Delivery",
            "cart" to "Cart",
            "chat" to "Chat",
            "profile" to "Profile",
            "welcome_back" to "Welcome back,",
            "categories" to "Categories",
            "top_new" to "Top New Products",
            "big_save" to "Big Save (Discounts)",
            "top_brands" to "Top Ethiopian Brands",
            "top_stores" to "Top Stores",
            "premium_brands" to "Premium Brands",
            "new_ads_store" to "New Ads Store",
            "popular" to "Popular Trending",
            "etb" to "ETB",
            "app_lock_title" to "Enter Secure PIN",
            "app_lock_set" to "Set App Lock PIN",
            "setup_2fa" to "Two-Factor Verification (2FA)",
            "verify_phone" to "Verify Phone Number",
            "enter_otp" to "Enter 4-Digit OTP",
            "resend_otp" to "Resend OTP",
            "submit" to "Submit",
            "verify" to "Verify",
            "upload_id" to "Upload Valid ID (National ID, License, or Passport)",
            "upload_license" to "Upload Business License & TIN",
            "upload_vehicle" to "Upload Vehicle Reg (Car/Motorcycle Paper)",
            "full_name" to "Full Name",
            "phone" to "Phone Number",
            "email" to "Email Address",
            "address" to "Address (Region, State/Zone, City, Kebele)",
            "business_name" to "Business / Store Name",
            "tin" to "TIN (Tax Identification Number)",
            "plate_number" to "License Plate Number",
            "register" to "Register Account",
            "onboarding_title" to "Onboarding & Verification",
            "pending_approval" to "Your Seller application is pending admin pre-approval. Please contact E-Suuq support.",
            "not_registered" to "You must complete registration and verify your account first.",
            "my_account" to "My Account",
            "my_store" to "My Store",
            "my_delivery" to "My Deliveries",
            "settings" to "Settings",
            "help_center" to "Help Center (24/7 Support)",
            "about" to "About E-Suuq",
            "logout" to "Log Out",
            "language" to "App Language",
            "theme_dark" to "Dark Mode",
            "theme_light" to "Light Mode",
            "enable_app_lock" to "Enable App Lock",
            "order_tracking" to "Order Tracking Map",
            "route_title" to "Delivery Route Visualization",
            "seller" to "Seller Store",
            "buyer" to "Your Delivery Point",
            "courier" to "Courier (Current)",
            "deliveries_processing" to "Processing",
            "deliveries_completed" to "Completed",
            "deliveries_cancelled" to "Cancelled",
            "track_order" to "Track Order",
            "store_analytics" to "Store Analytics",
            "income" to "Total Income",
            "products_sold" to "Products Sold",
            "visits" to "Store Visits",
            "add_product" to "Add New Product",
            "edit_product" to "Edit Product",
            "product_name" to "Product Name",
            "product_price" to "Price (ETB)",
            "product_stock" to "Stock Qty",
            "product_category" to "Category",
            "save" to "Save Product",
            "delete" to "Delete",
            "incoming_orders" to "Incoming Customer Orders",
            "prepare" to "Prepare Item",
            "handover" to "Handover to Delivery",
            "job_finder" to "Nearby Delivery Jobs",
            "distance" to "Distance",
            "distance_traveled" to "Distance Traveled",
            "accept_job" to "Accept Order",
            "start_delivery" to "Start Navigation",
            "mark_delivered" to "Mark as Delivered",
            "promo_code" to "Promo Code",
            "apply" to "Apply",
            "checkout" to "Proceed to Checkout",
            "place_order" to "Place Order",
            "payment_method" to "Payment Method",
            "delivery_address" to "Delivery Address",
            "cbe_birr" to "CBE Birr / Telebirr",
            "cash_on_delivery" to "Cash on Delivery",
            "support_chat" to "E-Suuq Live Support Desk",
            "ads_and_promotions" to "Promotional Ads & Analytics",
            "impressions" to "Impressions",
            "clicks" to "Clicks",
            "ctr" to "Click-Through Rate (CTR)",
            "feature_store" to "Promote Store on Home Banner",
            "pay_feature" to "Pay ETB 500 for 7 Days Feature"
        ),
        AppLanguage.AMHARIC to mapOf(
            "app_name" to "ኢ-ሱቅ (E-Suuq)",
            "tagline" to "ቀዳሚው የኢትዮጵያ ሱፐር-አፕ",
            "role_buyer" to "ገዢ (Buyer)",
            "role_seller" to "ሻጭ (Seller)",
            "role_delivery" to "አድራሽ (Delivery)",
            "home" to "መነሻ ገጽ",
            "search" to "ፈልግ",
            "manage_store" to "ሱቅ",
            "manage_delivery" to "ማድረሻ",
            "cart" to "ቅርጫት",
            "chat" to "መልዕክት",
            "profile" to "መገለጫ",
            "welcome_back" to "እንኳን ደህና መጡ፣",
            "categories" to "ምድቦች",
            "top_new" to "አዳዲስ ምርቶች",
            "big_save" to "ታላቅ ቅናሽ",
            "top_brands" to "ታዋቂ የኢትዮጵያ ብራንዶች",
            "top_stores" to "ታዋቂ ሱቆች",
            "premium_brands" to "ታዋቂ ብራንዶች",
            "new_ads_store" to "የአዳዲስ ሱቆች ማስታወቂያ",
            "popular" to "ተወዳጅ ምርቶች",
            "etb" to "ብር (ETB)",
            "app_lock_title" to "የደህንነት ፒን (PIN) ያስገቡ",
            "app_lock_set" to "የደህንነት ፒን ያዘጋጁ",
            "setup_2fa" to "ባለሁለት ደረጃ ማረጋገጫ (2FA)",
            "verify_phone" to "ስልክ ቁጥር ማረጋገጥ",
            "enter_otp" to "ባለ 4 አሃዝ ኮድ ያስገቡ",
            "resend_otp" to "ኮድ መልሰው ይላኩ",
            "submit" to "አስገባ",
            "verify" to "አረጋግጥ",
            "upload_id" to "መታወቂያ ያያይዙ (ብሔራዊ መታወቂያ፣ መንጃ ፈቃድ ወይም ፓስፖርት)",
            "upload_license" to "የንግድ ፈቃድ እና የግብር ከፋይ መለያ ቁጥር (TIN) ያያይዙ",
            "upload_vehicle" to "የተሽከርካሪ ባለቤትነት ማረጋገጫ (ሊብሬ) ያያይዙ",
            "full_name" to "ሙሉ ስም",
            "phone" to "ስልክ ቁጥር",
            "email" to "ኢሜይል አድራሻ",
            "address" to "አድራሻ (ክልል፣ ዞን፣ ከተማ፣ ቀበሌ)",
            "business_name" to "የሱቅ / የንግድ ስም",
            "tin" to "የግብር ከፋይ መለያ ቁጥር (TIN)",
            "plate_number" to "የሰሌዳ ቁጥር",
            "register" to "ይመዝገቡ",
            "onboarding_title" to "ምዝገባ እና ማረጋገጫ",
            "pending_approval" to "የሻጭነት ማመልከቻዎ በድርጅቱ ቁጥጥር ስር ነው። እባክዎ የኢ-ሱቅ ድጋፍን ያነጋግሩ።",
            "not_registered" to "በመጀመሪያ ምዝገባዎን ማጠናቀቅ እና መለያዎን ማረጋገጥ አለብዎት።",
            "my_account" to "የእኔ መለያ",
            "my_store" to "የእኔ ሱቅ",
            "my_delivery" to "የእኔ ማድረሻዎች",
            "settings" to "ቅንብሮች",
            "help_center" to "የእገዛ ማዕከል (የቀጥታ ውይይት)",
            "about" to "ስለ ኢ-ሱቅ",
            "logout" to "ውጣ",
            "language" to "የመተግበሪያ ቋንቋ",
            "theme_dark" to "ጨለማ ሁነታ",
            "theme_light" to "ብርሃን ሁነታ",
            "enable_app_lock" to "መተግበሪያውን ቆልፍ",
            "order_tracking" to "የቅደም ተከተል ካርታ",
            "route_title" to "የማድረሻ መስመር እይታ",
            "seller" to "የሻጭ ሱቅ",
            "buyer" to "የማድረሻ ነጥብዎ",
            "courier" to "አድራሽ (አሁን ያለበት ቦታ)",
            "deliveries_processing" to "በሂደት ላይ",
            "deliveries_completed" to "የተጠናቀቁ",
            "deliveries_cancelled" to "የተሰረዙ",
            "track_order" to "ትዕዛዝ ተከታተል",
            "store_analytics" to "የሱቅ ትንታኔ",
            "income" to "ጠቅላላ ገቢ",
            "products_sold" to "የተሸጡ ምርቶች",
            "visits" to "የሱቅ ጎብኝዎች",
            "add_product" to "አዲስ ምርት ጨምር",
            "edit_product" to "ምርት አስተካክል",
            "product_name" to "የምርት ስም",
            "product_price" to "ዋጋ (በብር)",
            "product_stock" to "የክምችት መጠን",
            "product_category" to "ምድብ",
            "save" to "ምርት አስቀምጥ",
            "delete" to "ሰርዝ",
            "incoming_orders" to "የገቡ ትዕዛዞች",
            "prepare" to "ምርት አዘጋጅ",
            "handover" to "ለአድራሽ አስረክብ",
            "job_finder" to "በአቅራቢያ ያሉ የማድረስ ስራዎች",
            "distance" to "ርቀት",
            "distance_traveled" to "የተጓዙት ርቀት",
            "accept_job" to "ትዕዛዝ ተቀበል",
            "start_delivery" to "ጉዞ ጀምር",
            "mark_delivered" to "ደረሰ ብለህ ምልክት አድርግ",
            "promo_code" to "የማስተዋወቂያ ኮድ",
            "apply" to "ተጠቀም",
            "checkout" to "ለመክፈል ቀጥል",
            "place_order" to "ትዕዛዝ ይፈጽሙ",
            "payment_method" to "የክፍያ አማራጭ",
            "delivery_address" to "የማድረሻ አድራሻ",
            "cbe_birr" to "ሲቢኢ ብር / ቴሌብር",
            "cash_on_delivery" to "እቃው ሲደርስ መክፈል",
            "support_chat" to "የኢ-ሱቅ የቀጥታ ድጋፍ",
            "ads_and_promotions" to "የማስታወቂያዎች ትንታኔ",
            "impressions" to "እይታዎች",
            "clicks" to "ክሊኮች",
            "ctr" to "የክሊክ መጠን (CTR)",
            "feature_store" to "ሱቁን በመነሻ ባነር ላይ ያስተዋውቁ",
            "pay_feature" to "ለ7 ቀናት ማስታወቂያ 500 ብር ይክፈሉ"
        ),
        AppLanguage.SOMALI to mapOf(
            "app_name" to "E-Suuq",
            "tagline" to "Super-App-ka Koowaad ee Itoobiya",
            "role_buyer" to "Iibsade",
            "role_seller" to "Iibiye",
            "role_delivery" to "Gaarsiiye",
            "home" to "Hoyga",
            "search" to "Raadi",
            "manage_store" to "Dukaan",
            "manage_delivery" to "Gaarsiinta",
            "cart" to "Gaariga",
            "chat" to "Sheeko",
            "profile" to "Hufnaanta",
            "welcome_back" to "Ku soo dhowaad,",
            "categories" to "Qaybaha",
            "top_new" to "Alaabta Cusub",
            "big_save" to "Dhimis Weyn",
            "top_brands" to "Astaamaha Itoobiya",
            "top_stores" to "Dukaamada Caanka Ah",
            "premium_brands" to "Astaamaha Filatamaa",
            "new_ads_store" to "Xayeysiiska Dukaamada Cusub",
            "popular" to "Alaabta Caanka Ah",
            "etb" to "ETB",
            "app_lock_title" to "Geli PIN-ka Amniga",
            "app_lock_set" to "Sameyso PIN-ka Amniga",
            "setup_2fa" to "Xaqiijinta Labada Tallaabo (2FA)",
            "verify_phone" to "Xaqiiji Lambarka Taleefanka",
            "enter_otp" to "Geli 4-Tiradood ee OTP",
            "resend_otp" to "Dib u dir OTP",
            "submit" to "Geli",
            "verify" to "Xaqiiji",
            "upload_id" to "Geli ID Aqoonsi (ID Qaran, Shatiga Darawalnimada, ama Baasaboor)",
            "upload_license" to "Geli Shatiga Ganacsiga & TIN",
            "upload_vehicle" to "Geli Diiwaangelinta Gaadhiga (Waraaqaha Libre)",
            "full_name" to "Magaca Buuxa",
            "phone" to "Lambarka Taleefanka",
            "email" to "Cinwaanka Email-ka",
            "address" to "Cinwaanka (Gobolka, Deegaanka, Magaalada, Kebele)",
            "business_name" to "Magaca Ganacsiga",
            "tin" to "TIN (Lambarka Canshuur bixiyaha)",
            "plate_number" to "Lambarka Taargada",
            "register" to "Diiwaangeli Koontada",
            "onboarding_title" to "Diiwaangelinta & Xaqiijinta",
            "pending_approval" to "Codsigaaga iibiyaha wuxuu sugayaa oggolaanshaha maamulka. Fadlan la xiriir taageerada E-Suuq.",
            "not_registered" to "Waa inaad marka hore dhammaystirtaa diiwaangelinta oo aad xaqiajisaa koontadaada.",
            "my_account" to "Koontadayda",
            "my_store" to "Dukaankayga",
            "my_delivery" to "Gaarsiintayda",
            "settings" to "Habeeyaha",
            "help_center" to "Xarunta Caawinaada (Wadahadal Toos ah)",
            "about" to "Ku saabsan E-Suuq",
            "logout" to "Ka Bax",
            "language" to "Luuqadda App-ka",
            "theme_dark" to "Qaabka Madow",
            "theme_light" to "Qaabka Cad",
            "enable_app_lock" to "Xidh App-ka",
            "order_tracking" to "Khariidadda Raadraaca Dalabka",
            "route_title" to "Muuqaalka Waddada Gaarsiinta",
            "seller" to "Dukaanka Iibiyaha",
            "buyer" to "Meesha Lagugu Geynayo",
            "courier" to "Gaarsiiyaha (Hadda)",
            "deliveries_processing" to "Hadda Socda",
            "deliveries_completed" to "Dhammaystirmay",
            "deliveries_cancelled" to "La Buriyey",
            "track_order" to "Raac Dalabka",
            "store_analytics" to "Falanqaynta Dukaanka",
            "income" to "Dakhliga Guud",
            "products_sold" to "Alaabta La Iibiyey",
            "visits" to "Booqashooyinka Dukaanka",
            "add_product" to "Kudar Alaab Cusub",
            "edit_product" to "Wax ka beddel Alaabta",
            "product_name" to "Magaca Alaabta",
            "product_price" to "Qiimaha (ETB)",
            "product_stock" to "Tirada Keydka",
            "product_category" to "Qaybta",
            "save" to "Keydi Alaabta",
            "delete" to "Tir",
            "incoming_orders" to "Dalabaadka Macmiilka ee Imanaya",
            "prepare" to "Diyaari Alaabta",
            "handover" to "U dhiib Gaarsiiyaha",
            "job_finder" to "Gaarsiinta Ka dhow ee Diyaarka ah",
            "distance" to "Fogaanta",
            "distance_traveled" to "Fogaanta La Socday",
            "accept_job" to "Aqbal Dalabka",
            "start_delivery" to "Bilow Socdaalka",
            "mark_delivered" to "U calaamadee in la geeyey",
            "promo_code" to "Koodhka Qiimo-dhimista",
            "apply" to "Codso",
            "checkout" to "U gudub Bixinta Qiimaha",
            "place_order" to "Gub dalabka",
            "payment_method" to "Habka Lacag Bixinta",
            "delivery_address" to "Cinwaanka Wax lagu Geynayo",
            "cbe_birr" to "CBE Birr / Telebirr",
            "cash_on_delivery" to "Lacag bixi markaad hesho alaabta",
            "support_chat" to "Taageerada Tooska ah ee E-Suuq",
            "ads_and_promotions" to "Xayeysiiska & Analytics-ka",
            "impressions" to "Aragtida",
            "clicks" to "Clicks-ka",
            "ctr" to "Heerka Clicks-ka (CTR)",
            "feature_store" to "Ku bandhig dukaanka bogga hore",
            "pay_feature" to "Bixi 500 ETB si loo xayeysiiyo 7 maalmood"
        )
    )

    fun get(key: String): String {
        return strings[language]?.get(key) ?: strings[AppLanguage.ENGLISH]?.get(key) ?: key
    }
}

val LocalLocalization: ProvidableCompositionLocal<Localization> = staticCompositionLocalOf {
    Localization(AppLanguage.ENGLISH)
}

@Composable
fun loc(key: String): String {
    return LocalLocalization.current.get(key)
}
